### ISSUE TITLE
dekimashitaリリース判定

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#54]
dekimashtiaをリリースして、グロースに集中し、そこで学んだことをエリーにも活かせられる。

ユーザー数（メールを受ける人）を10,000人を目指して、リリースまでにやるのか、リリース後でもいいのか。どこまでがMUSTでどこまでがWANTなのか。

まず私が気になっていることを書き出すことが大事だと思いますので、リストアップします。（ほかに気になることがありましたら、足してください）

このリストを全部クリアしたらdekimashitaが本リリースになります。

MUST
#### 広く知ってもらうためには他のどんな準備ができるのか
ープレスページ、ロゴの用意など
#### 入力ミスのキャッチ
ー間違って、samson.yee@synergy100.jpを入れるとどうなるのか
#### メールアドレスの入力支援はできないか
ー入力ミス防止にもつながるが、たとえば、@マークのあとをメンバー追加するときにデフォルトに埋めるとか
#### 何人いたらメールは長すぎるのか
ーそもそも１００人いたら送れるのか

**Comment by yoshi-takeda** [comment]
抜けが把握しにくいので、とりあえずみんなで気になるところを好きなだけ書いて、あとでカテゴライズしましょう

●ヤフー関連
●機能追加、改善
●テスト
●プロモーション

くらいかな

ーーーーーーー
・77つの壁は全てを満たそうと思うと物凄く時間がかかる項目があるので(外部機関のチェックをうけているかなど)
　おそらくすべてを満たすことが必須じゃないと思うので、ヤフーの人にどれくらい満たしていればリリースできるかは聞く必要があります

・ヤフー名義で出す場合、サイトやマニュアル、サイト内の文言チェックの依頼も必要

・1万ユーザを目指すとgoogleログイン、facebookログイン以外が必要なんじゃないかと思う

**Comment by saor1** [comment]
・画面遷移がFIXしているか
・ちょっとしたデザイン修正もまだ出てきそう

**Comment by macha3162** [comment]
運用体制を明確にしたい
⇛今後増えていくアプリを一人では見れないので
Awsに移行した時にDBはどうするのか
⇛月額の運用にいくらほどコストを掛けていいのかにも関係する

**Comment by yoshi-takeda** [comment]
増田さんが書いてるコスト絡みで予算上収まるかもチェックする（たぶんelliとかちびのあまりで許容できる範囲）

**Comment by yeesamson** [comment]
はい。

・エラー対応含めて、SLA（UPTIMEとRESPONSE TIME）をどこに持つのかははっきりする必要があると思います。
UPTIME 93%で、月に最大48時間（週末）がダウンしても許してもらえることになります。
RESPONSE TIMEは年中無休で問い合わせに対する返信は私がやりますので、ここは24時間にしましょう。

・Awsに移行した時にDBというのはAWSにあるDBという意味ですか。
・月額の運用費に関してははっきりした線はないが、月額数万円代に入ると会社と確認するようにします。

**Comment by saor1** [comment]
さっきハングアウトででてたところで
・効果測定（質問メール配信数の可視化)

・GAとか
・エラー画面、メンテナンス画面

**Comment by yoshi-takeda** [comment]
**4/25時点での概況**

#### ヤフー関連
- [ ] #62 ７７つの壁関連対応が終わったときに問題ないレベルかを確認する  
_→神田さんとやりとり中_
- [ ] #57 ヤフーのインキュベーション室という名前を使っていいのか確認する
- [ ] #56 ヤフーで出していい場合、サイト、サービス内の文言チェックを依頼する  
_→成果物が出揃ってからチェックを依頼するので今は放置_

#### 規約、セキュリティ
- [ ] #43 規約、ポリシーの作成、明示  
_→法務部に依頼済み。今週中目処に返事うけてアップデート。大きな修正発生しない見込み_
- [ ] #58 SLAの作成、明示   
_→4/26竹田&増田で内容をFIXさせる_
- [ ] #48 メールセキュリティの向上   
_→増田さん着手中。AWSへの移行込み_
- [ ] #45 ステータスページを作る  
_→津田さんアサイン_
- [ ] #73 アップデート内容の通知手段を設ける  
_→未着手_

#### 機能追加、改善
- [ ] #53 キーワード転送機能を実装する   
_→未着手。実施有無を決める必要あり_
- [ ] #65 画面遷移をFIX  
_→津田さんアサイン_
- [ ] #69 デザイン修正をFIX  
_→津田さんアサイン。随時消化_
- [ ] #66 googleログイン、facebookログイン以外のサインアップ方法を作る  
_→見積もり追記(1.5人日)。実施タイミングを決める必要あり_
- [ ] #60 エラー画面、メンテナンス画面を作る  
_→津田さんアサイン_
- [ ] #61 マネシスを作る   
_→津田さんアサイン_
- [ ] #32 メールアドレスの入力支援機能(@マークのあとをデフォルトで埋めるとか)　  
_→吉田さんアサイン_
- [ ] #22 パース処理改善   
_→吉田さんアサイン_

#### フィードバック、アナリティクス
- [x] #63 フィードバックを集める仕組みを入れる  
_→不要としてクローズ_
- [ ] #64 USAGEデータを見える化する(GA、マネシスでの表示など)  
_→どんなデータを集めるか決定する必要あり_

#### テスト
- [ ] #67 単体テスト(間違って、samson.yee@synergy100.jpを入れるとどうなるのかとか)
- [ ] #67 結合テスト  
_→佐藤さんチームの工数確保。修正がある程度終わった時点で実施を依頼。_
- [ ] #68 パフォーマンステスト(100人にメール送れる？、回答めっちゃ長いとか)  
_→未着手。竹田&増田で実施予定_

#### プロモーション  
_→諸々未着手_
- [ ] #70 ホームページの説明を充実させる
- [ ] 広く知ってもらうための準備
- [ ] プレスページ
- [ ] ロゴの用意

#### その他
- [ ] BETA版と呼ぶかどうか。BETAのメリット・デメリットを検討する
